# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'Notes-CoreData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Notes-CoreData
  pod 'SwiftLint'

  target 'Notes-CoreDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Notes-CoreDataUITests' do
    # Pods for testing
  end

end
